### PR TITLE
Reorganizing the repo structure

### PR DESCRIPTION
**Pull request by rchung95**
# Changes
In this PR, I:
* Reorganized the repository's structure to follow the consistency of Python, Git and Shell repositories
* Replaced dashes with snake case

### CODE REVIEW

**Comment by mrpotatocode** [comment]
@rchung95, some good suggestions I have also been considering!
However, these changes have annoying upstream effects that do not make sense to address mid-term. Will review again at end of March.

I might argue that 06-SQL should come before 05-Data, as the data folder is only used in one lecture out of six. 

Also, I will not remove the HTML slides as they are what I teach from.

**Comment by rchung95** [comment]
@mrpotatocode I am not merging this into the repo right away. I am just organizing this repo to be consistent with the other repo format structure.

**Comment by mrpotatocode** [comment]
> Interesting, let me to talk to Dan as we usually want to have all courses be consistently a single format everyone uses.

The reason for HTML is because these slides are generated (and written) in R. There are huge advantages to this and create a much better quality slide deck than a standard pdf-based deck. (In other words, there is actually pedagogical value from using the HTMLs instead of the PDFs). The PDFs are then generated for students' convenience and ease of use after lectures have concluded.

This is also why the repo re-org has these upstream affects (which are not overly complex to change, but does require my labour.) Since I'm in agreement that it'd be great to use the 01-, 02-, 03-, etc folder structure, I am glad to do that work, but would prefer to do the merge myself (i.e. let me fix all the dependencies first, and then we can merge). We can chat about it Friday :)

**Comment by rchung95** [comment]
> > Interesting, let me to talk to Dan as we usually want to have all courses be consistently a single format everyone uses.
> 
> The reason for HTML is because these slides are generated (and written) in R. There are huge advantages to this and create a much better quality slide deck than a standard pdf-based deck. (In other words, there is actually pedagogical value from using the HTMLs instead of the PDFs). The PDFs are then generated for students' convenience and ease of use after lectures have concluded.
> 
> This is also why the repo re-org has these upstream effects (which are not overly complex to change, but does require my labour to resolve.) Since I'm in agreement that it'd be great to use the 01-, 02-, 03-, etc folder structure [wish I had done it two years ago lol], I am glad to do that work, but would prefer to do the merge myself (i.e. let me fix all the dependencies first, and then we can merge). We can chat about it Friday :)

Yes, let's chat Friday. For now, I will just open up the PR with the changes, and we will go from there. The reasoning is even if you do the changes, you have the closed PRs to use as reference.

**Comment by mrpotatocode** [comment]
>  The reasoning is even if you do the changes, you have the closed PRs to use as reference.

Very much appreciate this! 🚀

**Review by danielrazavi — APPROVED** [review]

**Comment by danielrazavi** [comment]
Reviewed, Approved and Merging in.

**Pull request merged**
