### PR TITLE
Assignment two SQL Completed

### PR DESCRIPTION
**Pull request by rashitakalra**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
I was adding SQL commands and learning SQL queries.

## What did you learn from the changes you have made?
I learnt running SQL.

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
No.

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
Yes, since I am new I faced challenge in understanding certain things. 

## How were these changes tested?
By running on SQLlite DB.

## A reference to a related issue in your repository (if applicable)
NA

## Checklist
- [x] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by mrpotatocode** [comment]
Hi. You have unfortunately made a pull request to the wrong repo. You shouldn't be making a pull request to uoft-dsi/sql, but rather your own forked sql repo. Please see further instructions on your onboarding [Assignment Submission Guide](https://github.com/UofT-DSI/onboarding/blob/main/onboarding_documents/submissions.md).

**Comment by rashitakalra** [comment]
Hi,

Apologies.
I have resubmitted the assignment. Looking forward to your confirmation if
the assignment has been submitted correctly.

Warm regards
Rashita

**Comment by efantinatti** [comment]
Hi @rashitakalra looks like your commit didn't went through (it was on UofT's repo). Please commit it to your repo.

**Comment by rashitakalra** [comment]
Hi,

Can you please guide if I should create a new branch and resubmit the
assignment again or i can modify the existing assignment as I am getting
confused.
Warm Regards
Rashita

**Comment by efantinatti** [comment]
Hi Rashita

You must commit it to your own repo (see your username there) and not to
the UofT's repo.

Best regards
Ernani Fantinatti

**Comment by rashitakalra** [comment]
Hi Ernani,

Please find below two links for my completed assignment 2.

1. The below link corresponds to the github assignment two branch where I
have completed my assignment.

https://github.com/rashitakalra/sql/blob/assignment-two/02_activities/assignments/assignment2.sql%20completed

2. The below link refers to the pull request I made on the updated
assignment in my Repo.

https://github.com/rashitakalra/sql/pull/2

Please see if the assignment is correct.

Warm Regards
Rashita

**Comment by rashitakalra** [comment]
Hi Ernani

Please confirm if the assignment is submitted correctly based on the links
I have shared below considering tomorrow is the deadline for submission.

Regards
Rashita

**Comment by efantinatti** [comment]
Hi Rashita

Looks like your assignment was committed to the wrong repo (UofT). Please
check it out.

Also your reviewer is Nyiaz. Please reach out to her.

Best regards
Ernani Fantinatti

**Comment by rashitakalra** [comment]
Dear Fakhteh and team,

Greetings for the day.

Kindly note that I have made the changes to the assignment and submitted
through my repository.
Please check the completed assignment through below links.
https://github.com/rashitakalra/sql/blob/assignment-two/02_activities/assignments/assignment2.sql%20completed
https://github.com/rashitakalra/sql/pull/2

I would request you to kindly check and confirm if you have received the
assignment correctly. Or I shall delete the branch and redo the
assignment so it is submitted correctly as I have finished the assignment
on my end and I don't want the module to be marked as incomplete. I would
really appreciate your prompt response considering the deadline is 30th
December 2024.

Awaiting your response and assistance.

Warm Regards
Rashita

**Pull request closed without merging**
