### PR TITLE
PROPOSED Cohort five homework changes -- do not merge

### PR DESCRIPTION
**Pull request by mrpotatocode**
Please review Assignment1.md and Assignment2.md

Corresponding assignment1.sql and assignment2.sql are just the .sql scripts for sections 2&3.

In this build, we have 0 homeworks, and 2 assignments total.

Let me know thoughts and then I can finalize the branch. I will reopen a PR to actually merge, so please don't merge this one :D

### CODE REVIEW

**Comment by mrpotatocode** [comment]
@moejennie , @RohanAlexander  @danielrazavi  for review only please. this removes homeworks, and creates 2 assignments.

**Review by danielrazavi — CHANGES_REQUESTED** [review]
I love the assignments. I think they're great! One tiny change though: SQL is a module, and they have different sessions with you, so the terminology should be updated in that regard. Other than that, it looks great to me.

**Comment by mrpotatocode** [comment]
All 'module' --> 'session' changes done

Updated pull to pulls

Added relative paths for the .sql file links (instead of just linking to main branch)

**Comment by mrpotatocode** [comment]
Closing without merging, will reopen with all requested changes and added rubrics

**Pull request closed without merging**
