### PR TITLE
Homework1

### PR DESCRIPTION
**Pull request by cecily-li**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
added a file for logical model (SQL homework 1)
## What did you learn from the changes you have made?
importance of understanding entity relationships before going in to make changes or use the model 
## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
hand drawing, but used draw.io because of formatting and ease of use. 
## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
n/a
## How were these changes tested?
n/a
## A reference to a related issue in your repository (if applicable)
n/a

## Checklist
- [ x] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by cecily-li** [comment]
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
added sql file for homework 2

## What did you learn from the changes you have made?
there is more than one way to arrive at the same outcome (query structure wise)

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
see "NOTEs" comments in sql file

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
see "NOTEs" comments in sql file

## How were these changes tested?
tested standalone queries in a second SQL file 

## A reference to a related issue in your repository (if applicable)
n/a

## Checklist
- [ ] I can confirm that my changes are working as intended

**Comment by cecily-li** [comment]
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
changes to HW3 SQL file, new temp table in db

## What did you learn from the changes you have made?
it is really important to understand the dataset before you go in and manipulate/use the data

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
n/a

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
challenges in syntax, overcame using class resources and the web

## How were these changes tested?
tested by running queries in separate SQL file before pasting back into homework 3 sql

## A reference to a related issue in your repository (if applicable)
n/a

## Checklist
- [ x] I can confirm that my changes are working as intended

**Comment by cecily-li** [comment]
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
changes to HW3 SQL file, new temp table in db

## What did you learn from the changes you have made?
it is really important to understand the dataset before you go in and manipulate/use the data

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
n/a

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
challenges in syntax, overcame using class resources and the web

## How were these changes tested?
tested by running queries in separate SQL file before pasting back into homework 3 sql

## A reference to a related issue in your repository (if applicable)
n/a

## Checklist
- [ x] I can confirm that my changes are working as intended

**Comment by danielrazavi** [comment]
You have unfortunately made a pull request to the wrong repo. You shouldn't be making a pull request to uoft-dsi/sql, but rather your own forked sql repo. Please read the instructions on your onboarding [Assignment Submission Guide](https://github.com/UofT-DSI/onboarding/blob/main/onboarding_documents/submissions.md) more carefully.

**Review by amanda-ng518 — COMMENTED** [review]
HW1: good, 8/8

**Review by amanda-ng518 — COMMENTED** [review]
HW2: good, 8/8

**Review by amanda-ng518 — COMMENTED** [review]
HW3: 
AGGREGATE Q2 use LEFT JOIN
7/8

**Pull request closed without merging**
