### PR TITLE
Updating the Folder Structure

### PR DESCRIPTION
**Pull request by danielrazavi**
### Pull Request Description

**Summary:**
This PR reorganizes the folder structure to enhance clarity and consistency across all repositories. The following changes have been made:

1. **Renamed and Reorganized Folders:**
   - `01_slides` is now `01_materials` containing `slides`.
   - `02_assignments` and `03_homeworks` are now inside of `02_activities` as `assignments` and `homework`.
   - `06_instructional_team` is now `03_instructional_team`.
   - `07_cohort_three` is now `04_cohort_three`.
   - `05_sql` and `04_data` are now inside of `05_src` as `sql` and `data`
4. **Updated Descriptions to the below template**

**New Folder Structure:**

```markdown
.
├── .github
├── 01_materials
│   ├── slides
│   └── labs
├── 02_activities
│   ├── assignments
│   ├── exercises
│   └── homework
├── 03_instructional_team
├── 04_cohort_three
├── 05_src
│   ├── sql
│   ├── logs
│   ├── data
│   └── requirements.txt
├── .gitignore
├── LICENSE
├── README.md
└── steps_to_ask_for_help.png
```

**Details:**
* **.github**: Contains issue templates and pull request templates for the repository.
* **materials**: Module slides and interactive notebooks (.ipynb files) used during learning sessions.
* **activities**: Contains graded assignments, exercises, and homework to practice concepts covered in the learning module.
* **instructional_team**: Resources for the instructional team.
* **cohort_three**: Additional materials and resources for cohort three.
* **src**: Source code, databases, logs, and required dependencies (requirements.txt) needed during the module.
* **.gitignore**: Files to exclude from this folder, specified by the Technical Facilitator
* **LICENSE**: The license for this repository.
* **README**: This file.
* **steps_to_ask_for_help.png**: Guide on how to ask for help.

Please review the changes and provide feedback. Thank you!
## Checklist
- [X] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by mrpotatocode** [comment]
@danielrazavi , broadly these changes are fine, but let me remind you that every time links change, I have to update tons of supplement materials to reference them -- it's a lot of labour wasted if we're doing it every cohort

**Comment by danielrazavi** [comment]
@mrpotatocode I'm making sure every single one of these links work and making sure that you are not bothered by them. These changes are not something we are expecting to happen every cohort, they are simply some lessons learned from cohort 2.

**Comment by mrpotatocode** [comment]
There are non-GH supplementals -- like the Etherpad for example

**Comment by danielrazavi** [comment]
If the changes are needed on the Etherpad side, then you're right, it will create some manual work. That being said, as previously mentioned, this is most likely the last great change on our repos. On the Github, side we will make sure to update all links and addresses so that they are functional. We're sorry for the inconvenience.

**Comment by mrpotatocode** [comment]
All good. More of a reminder/request to keep big restructures to a minimum, which I think we've done well at, but I'm not sure what we'll end up doing with like a cohort 4 folder, etc. Just little questions to figure out :) 

Hope you're enjoying summer!

**Comment by danielrazavi** [comment]
We'll make sure to create the necessary actions for the cohort 3 folder. As of right now, two solutions come to mind: one, we simply add a cohort 4 folder and ask TF to populate it accordingly, setting a precedent for following cohorts to do the same; or two, we rename the cohort 3 folder to "extras" and allow TFs to have full control of the folder, establishing this as the new precedent.

**Comment by danielrazavi** [comment]
For now, we will merge the changes to match other repos.

**Review by moejennie — APPROVED** [review]
looks good to me

**Pull request merged**
