### PR TITLE
Update homework_1.md

### PR DESCRIPTION
**Pull request by lllllwang1**
I added PNG file.

## Checklist
- [ ] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by danielrazavi** [comment]
You have unfortunately made a pull request to the wrong repo. You shouldn't be making a pull request to uoft-dsi/sql, but rather your own forked sql repo. Please read the instructions on your onboarding [Assignment Submission Guide](https://github.com/UofT-DSI/onboarding/blob/main/onboarding_documents/submissions.md) more carefully.

**Comment by lllllwang1** [comment]
Hi Daniel,Thanks for letting me know the mistake! How could i remove that pull request and do i need to pull request again under my own repository?Thanks in advance!Shaohe Wang在 2024年5月21日，09:33，Daniel Razavi ***@***.***> 写道：﻿
You have unfortunately made a pull request to the wrong repo. You shouldn't be making a pull request to uoft-dsi/sql, but rather your own forked sql repo. Please read the instructions on your onboarding Assignment Submission Guide more carefully.

**Comment by danielrazavi** [comment]
I have already closed this PR. Yes you need to make a PR on your own repo. Please read the instructions on your onboarding [Assignment Submission Guide](https://github.com/UofT-DSI/onboarding/blob/main/onboarding_documents/submissions.md) more carefully.

**Comment by lllllwang1** [comment]
Thanks Daniel. Please see my new request of homework1.

Shaohe Wang

**Pull request closed without merging**
